[tool.bumpversion]
current_version = "0.0.1" # this is the single source of truth for the version

# do not create tags or commits by default
commit = false
tag = false
# allow to bump version even if there are uncommitted changes
allow_dirty = true


# parser
# either YYYY.MM.MICRO or YYYY.MM.MICRO-build.date.COMMIT_SHA
parse = "(?P<year>\\d+)\\.(?P<month>\\d+)\\.(?P<micro>\\d+)(?:\\-(?P<dev>release|build)\\.[0-9a-zA-Z-]+)?"


serialize = [
    "{year}.{month}.{micro}-{dev}.{now:%D-%H-%M}.{$SHORT_COMMIT_SHA}", # the serializer for dev builds; commit SHA is env variable;
    # note that builds cannot be incremented!
    # this is purely for covenience of building intermediate versions without actually bumping the version in the codebase
    "{year}.{month}.{micro}" # serializer for actual releases
]

[tool.bumpversion.parts.dev]
# first value is optional and hence omitted from version output
# only build will appear in output if necessary
values = ["release", "build"]



