[tool.bumpversion]
current_version = "0.0.3"

# do not create tags or commits by default
commit = false
tag = false
allow_dirty = true
# parser
parse = "(?P<year>\\d+)\\.(?P<month>\\d+)\\.(?P<id>\\d+)\\-(?P<dev>release|build)\\.[0-9a-zA-Z-]+?"
serialize = [
    "{year}.{month}.{id}-{dev}.{$SHORT_COMMIT_SHA}", # commit SHA is env variable
    "{year}.{month}.{id}"
]


[tool.bumpversion.parts.dev]
# first value is optional and hence omitted from version output
# only build will appear in output if necessary
values = ["release", "build"]



