[tool.bumpversion]
current_version = "2.7.0"
commit = false
tag = false
allow_dirty = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:\\.(?P<dev>release|build)\\.[0-9a-zA-Z-]+)?"
serialize = [
    "{major}.{minor}.{patch}.{dev}.{commit_sha}",
    "{major}.{minor}.{patch}"
]


[tool.bumpversion.parts.dev]
values = ["release", "build"]


