[tool.bumpversion]
current_version = "0.0.1"
commit = false
tag = false
allow_dirty = true
parse = """
(?x)
    (?P<year>[0-9]+)
    \\.(?P<month>[0-9]+)
    \\.(?P<id>[0-9]+)
    (?:
    \\-(?P<dev>build)
    \\.(?P<build_id>[0-9]+)
    \\.(?P<commit_sha>[a-f0-9]+)
    )

    ?

"""
serialize = [
    "{year}.{month}.{id}-{dev}.{build_id}.sha{commit_sha}",
    "{year}.{month}.{id}",

]


[[tool.bumpversion.files]]
glob = "*/setup.py"



