name: airo-mono
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - -e airo-typing/
    - -e airo-spatial-algebra/
    - -e airo-camera-toolkit/
    - -e airo-robots/
    - -e airo-dataset-tools/
    - -e airo-teleop/

