site_name: Test
site_url: https://example.com

nav:
  - Home: index.md
  - airo-typing: '!include ./airo-typing/mkdocs.yaml'
  - airo-spatial-algebra: '!include ./airo-spatial-algebra/mkdocs.yaml'
  - airo-robots: '!include ./airo-robots/mkdocs.yaml'

plugins:
  - monorepo
  - mkdocstrings:
      #enabled: true
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_submodules: false
            members_order: source
            docstring_section_style: list
            show_if_no_docstring: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            heading_level: 2


theme:
  name: "material"