[mypy]
# disable errors for third-party libraries that do not provide typing (scipy, spatial-mathlib,..)
ignore_missing_imports = True
# pip install creates a build folder (see https://github.com/pypa/pip/issues/8165 )
# ignore this to avoid 'duplicate module named' errors
exclude = build
# namespace pacakges omit the need to put init files everywhere,
# cf PEP420 or https://stackoverflow.com/questions/62831486/requirement-for-init-py-just-to-satisfy-pylint-and-mypy
# without this flag, mypy would ignore such packages and only check if there is a namespace package
namespace_packages = True
