name: static type checking

on: [pull_request]

jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install ".[develop]"
    - name: Run type checker
      run: make mypy