name: Run stgtic type checking

on: [pull_request]

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install airo_core[develop]
    - name: Run type checker
      run: make mypy