name: static type checking

on:
  pull_request:
  push:
    branches:
      - main
      - ci-dev

jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [airo-typing,airo-spatial-algebra,airo-camera-toolkit, airo-robots, airo-teleop,airo-dataset-tools] #TODO: autodiscover?
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install ${{matrix.package}}/[external]
    - name: Run type checker
      run: mypy ${{matrix.package}}/