name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - ci-dev

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        #os: [ubuntu-latest, windows-latest, macos-latest] # avoid this cost untill it becomes necessary..
        package: [airo-typing,airo-spatial-algebra, airo-camera-toolkit, airo-robots, airo-dataset-tools] #TODO: autodiscover?
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install workspace
      run: uv sync --python ${{ matrix.python-version }} --all-packages
    - name: Run Tests
      run: uv run pytest ${{matrix.package}}/
    - name: Run Notebooks
      # cannot use glob patter because that fails if no notebooks are found (in which case the glob pattern is empty.)
      # so cannot do something like pytest --nbmake ${{matrix.package}}/**/*.ipynb
      # and we also don't want to re-execute all regular tests (pytest --nbmake .)
      # so manually iterate over all files and run pytest --nbmake on each one.

      # don't forget to enable glob! https://github.com/orgs/community/discussions/25638
      run: |
        uv run python -m ipykernel install --user --name airo-mono
        shopt -s globstar nullglob
        echo "Testing notebooks..."
        for nb in ${{matrix.package}}/**/*.ipynb; do
          uv run pytest --nbmake $nb;
        done
